name: Deploy to GitHub Pages

# déclenche l'action manuellement après un push sur la branche main
on: 
  workflow_dispatch:
    branches:
      - main

# définition des permissions et autorisation de permettre le deploy sur GitHub Pages
permissions:
  contents: read
  pages: write

# autorise un déploiement à la fois
concurrency:
  group: 'pages'
  cancel-in-progress: true

# définition des étapes d'intégration et de déploiement
jobs:
  # étape d'intégration
  build:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      # Récupération du code du projet (= git clone)
      - name: Fetch code
        uses: actions/checkout@v4

      # installation des dépendances
      - name: Install dependencies
        run: npm install

      # build du projet (transpilation ts -> js...)
      - name: Build
        run: npm run build

      # Charger artefact vers GitHub Pages
      - name: Upload artefact to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          name: artifact
          path: ./dist
  
  deploy:
    # étape de déploiement
    runs-on: ubuntu-latest
    needs: build # (pour faire deploy on a besoin que build soit ok et ce soit bien passé)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # configuration de GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: artifact