name: Deploy to surge

on:
  push:
    branches:
      - main

# définition des permissions et autorisation de permettre le deploy sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# autorise un déploiement à la fois
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  buildNdeploy:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      # Récupération du code du projet (= git clone)
      - name: Fetch code
        uses: actions/checkout@v4

      # installation des dépendances
      - name: Install dependencies
        run: npm install

      # build du projet (transpilation ts -> js...)
      - name: Build
        run: npm run build

      # déploiement sur Surge
      - name: Deploy to Surge
        run: |
          npm install -g surge
          surge ./dist react-avec-poulette.surge.sh/
